import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    // 完全自动生成侧边栏
    { type: 'autogenerated', dirName: '.' },
  ],
};

export default sidebars;